name: Run Airflow Dags Python Syntax Check

on:
  pull_request:
    paths:
      - 'data_dag/**'
      - 'data_sharing/**'

env:
  AIRFLOW_VAR_CRADLE_CLUSTER_ID: j-xxxxxx
  AIRFLOW_VAR_REDIS_STG_HOST: dummy-host
  AIRFLOW_VAR_REDIS_PRD_HOST: dummy-host
  AIRFLOW_VAR_ENVIRONMENT: stg

jobs:
  syntax-check-data_dag:
    if: ${{ github.event.pull_request.changed_files != 0 && github.event.pull_request.changed_files | contains('.py') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r ./mwaa/requirements/requirements.txt
      - name: Pipeline syntax check for data_dag
        run: |
          for file in $(git diff --name-only ${{ github.sha }} ${{ github.event.pull_request.base.sha }} -- ./data_dag/dags/**/*_dag.py); do
            python3 -m py_compile $file
          done

  syntax-check-data_sharing:
    if: ${{ github.event.pull_request.changed_files != 0 && github.event.pull_request.changed_files | contains('.py') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r ./mwaa/requirements/requirements.txt
      - name: Pipeline syntax check for data_sharing
        run: |
          for file in $(git diff --name-only ${{ github.sha }} ${{ github.event.pull_request.base.sha }} -- ./data_sharing/dags/**/*_dag.py); do
            python3 -m py_compile $file
          done
