name: Run Airflow Dags Python Syntax Check

on:
  pull_request:
    paths:
      - '/mwaa/data_dags/**/*.py'

env:
  AIRFLOW_VAR_CRADLE_CLUSTER_ID: j-xxxxxx
  AIRFLOW_VAR_REDIS_STG_HOST: dummy-host
  AIRFLOW_VAR_REDIS_PRD_HOST: dummy-host
  AIRFLOW_VAR_ENVIRONMENT: stg

jobs:
  syntax-check-data_dag:
    if: contains(github.event.pull_request.files.*.filename, '/mwaa/data_dags/')
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r ./test_ci/requirements.txt
      - name: Pipeline syntax check for data_dag
        run: |
          git diff --name-only HEAD^ HEAD | grep '\.py$' | while read file; do
            python3 -m py_compile "$file"
          done
